### PR TITLE
visitor counter has changed

### PR DESCRIPTION
**Pull request by YahefuYusufu**
if you like it you can use this version,thank
Screenshot 2023-01-07 at 09 18 23

### CODE REVIEW

**Comment by diva-21** [comment]
May i know it only effects to the color or count will become 0??

**Comment by YahefuYusufu** [comment]
Unfortunately ,it effects your count ,but i dont think that it effects your color.
but it looks awesome ,

**Comment by YahefuYusufu** [comment]
yes, color as well . Sorry , i didn’t see that ,
but probably you can change the color

**Comment by diva-21** [comment]
Understood, thanks for the share. I dont want to change my readme right now. When i am willing to change, i will contact you

**Comment by diva-21** [comment]
@YusufYakup , you can work on different web projects. And join communities for further development. Be active on Twitter

**Pull request closed without merging**
